services:
   db:
     image: postgres:latest
     container_name: postgres_db
     restart: always
     ports:
       - 5432:5432
     environment:
       POSTGRES_USERNAME: postgres
       POSTGRES_PASSWORD: teste123
       POSTGRES_MULTIPLE_DATABASES: db_produtos, db_clientes, db_pedidos, db_entregas, db_pagamentos, authorization_server, sonar
     volumes:
       - ./scripts/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
       - ./postgres:/var/lib/postgresql/data
     healthcheck:
       test: [ "CMD-SHELL", "pg_isready -U postgres" ]
       interval: 5s
       timeout: 5s
       retries: 5

   sonarqube:
     image: sonarqube:latest
     depends_on:
       - db
     environment:
       SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
       SONAR_JDBC_USERNAME: postgres
       SONAR_JDBC_PASSWORD: teste123
       SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
     volumes:
       - sonarqube_data:/opt/sonarqube/data
       - sonarqube_extensions:/opt/sonarqube/extensions
       - sonarqube_logs:/opt/sonarqube/logs
     ports:
       - "9090:9000"
volumes:
   sonarqube_data:
   sonarqube_extensions:
   sonarqube_logs:
